/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoool.management.system.Arrangement_Group;

import schoool.management.system.Menu_Group.Welcome_Admin;
import schoool.management.system.Menu_Group.Welcome_Staff;
import schoool.management.system.Menu_Group.Welcome_Student;
import schoool.management.system.Tool_Group.Checking_Input_Data;
import schoool.management.system.Tool_Group.ConnectionClass;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.util.ArrayList;

/**
 * @author PC
 */
public class Class_Allocation extends javax.swing.JFrame {
    DefaultTableModel model;
    private static boolean showTime = true;
    private static int role = 0;
    private static String ID = null;
    private static int real_ID = 0;

    public static int getReal_ID() {
        return real_ID;
    }

    public static void setReal_ID(int real_ID) {
        Class_Allocation.real_ID = real_ID;
    }

    public static int getRole() {
        return role;
    }

    public static void setRole(int role) {
        Class_Allocation.role = role;
    }

    public static String getID() {
        return ID;
    }

    public static void setID(String ID) {
        Class_Allocation.ID = ID;
    }

    /**
     * Creates new form Class_Allocation
     */
    public Class_Allocation() {
        JLabel background = new JLabel(new ImageIcon("src/images/school theme 2.3.jpg"));
        setContentPane(background);
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        if (role == 0 || role == 1){
            btnRun.setEnabled(false);
        }
    }

    public ArrayList<Allocation> allocationArrayList() {
        ArrayList<Allocation> allocationArrayList = new ArrayList<>();
        try {
            Connection connection = ConnectionClass.connection();
            String sql = "SELECT * FROM Class_allocation";
            Statement preparedStatement = connection.createStatement();
            ResultSet rs = preparedStatement.executeQuery(sql);
            Allocation allocation;
            while (rs.next()) {
                allocation = new Allocation(
                        rs.getInt("enrollment_ID"),
                        rs.getString("subject_ID"),
                        rs.getInt("staff_ID"),
                        rs.getInt("student_ID"),
                        rs.getString("class_ID"),
                        rs.getString("room"));
                allocationArrayList.add(allocation);
            }
            connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return allocationArrayList;
    }

    public void show_allocation() {
        ArrayList<Allocation> list = allocationArrayList();
        model = (DefaultTableModel) tableShowAllocation.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getEnrollment_ID();
            row[1] = list.get(i).getSubject_ID();
            row[2] = list.get(i).getStaff_ID();
            row[3] = list.get(i).getStudent_ID();
            row[4] = list.get(i).getClass_ID();
            row[5] = list.get(i).getRoom();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboboxWhatToDo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnrollmentID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowAllocation = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboboxWhatToDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboboxWhatToDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Remove", "Update" }));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel2.setText("What to do:");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel7.setText("Staff ID:");

        txtStaffID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffIDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel9.setText("Room:");

        txtRoom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel4.setText("Enrollment ID:");

        txtEnrollmentID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Note:");

        jLabel3.setText("- These fields above are used to update an existed classroom information.");

        jLabel5.setText("- Can update by Subject ID only, browse for existed Subject IDs.");

        btnBrowse.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnRun.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        jLabel8.setText("- If you want to remove an allocation (a specific student enrollment),  then");

        jLabel10.setText("enter Enrollment ID only.");

        tableShowAllocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment ID", "Subject ID", "Staff ID", "Student ID", "Class ID", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableShowAllocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableShowAllocationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableShowAllocation);

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel11.setText("Class Allocation");

        btnMenu.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 10)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnMenu)
                .addGap(301, 301, 301)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRun))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtEnrollmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboboxWhatToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStaffID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(jLabel11))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboboxWhatToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtEnrollmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBrowse)
                            .addComponent(btnRun)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        if (showTime) {
            show_allocation();
            showTime = false;
        } else {
            model.setRowCount(0);
            show_allocation();
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        showTime = true;
        dispose();
        if (role == 0) {
            Welcome_Student.main(new String[]{});
        } else if (role == 1) {
            Welcome_Staff.main(new String[]{});
        } else {
            Welcome_Admin.main(new String[]{});
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void tableShowAllocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableShowAllocationMouseClicked
        // TODO add your handling code here:
        int i = tableShowAllocation.getSelectedRow();
        TableModel model = tableShowAllocation.getModel();
        txtEnrollmentID.setText(model.getValueAt(i, 0).toString());
        txtStaffID.setText(model.getValueAt(i, 2).toString());
        txtRoom.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tableShowAllocationMouseClicked

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
        if (comboboxWhatToDo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You need to choose an action!",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String doing = comboboxWhatToDo.getSelectedItem().toString();

        if (doing.equals("Add")) {
            if (txtEnrollmentID.getText().length() == 0 || txtStaffID.getText().length() == 0
                    || txtRoom.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "No field can be empty!",
                        "Warning!", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    if (Checking_Input_Data.Check("enrollment_ID", txtEnrollmentID.getText(),
                            "Class_allocation", false)
                            && !Checking_Input_Data.Check("enrollment_ID", txtEnrollmentID.getText(),
                            "Check_student_enrollment",
                            "Student must register before can be being allocated!", true)){
                        Connection con = ConnectionClass.connection();
                        String findStudentID =
                                "SELECT * FROM Check_student_enrollment WHERE enrollment_ID = "
                                        + txtEnrollmentID.getText();
                        Statement statement = con.createStatement();
                        ResultSet resultSet = statement.executeQuery(findStudentID);
                        resultSet.next();
                        String tempStudentID = resultSet.getString("student_ID");
                        int temp2StudentID = resultSet.getInt("student_ID");

                        String findClassID =
                                "SELECT * FROM Student WHERE student_ID = " + temp2StudentID;
                        Statement statement1 = con.createStatement();
                        ResultSet resultSet1 = statement1.executeQuery(findClassID);
                        resultSet1.next();
                        String tempClassID = resultSet1.getString("class_ID");

                        String findSubjectID =
                                "SELECT * FROM Check_student_enrollment WHERE enrollment_ID = '"
                                        + txtEnrollmentID.getText()
                                        +"'";
                        Statement statement2 = con.createStatement();
                        ResultSet resultSet2 = statement2.executeQuery(findSubjectID);
                        resultSet2.next();
                        String tempSubjectID = resultSet2.getString("subject_ID");
                        con.close();
                        if (Checking_Input_Data.Check("staff_ID", txtStaffID.getText(), "Staff", true)){
                            JOptionPane.showMessageDialog(null,
                                    "This Staff is not available, \ncheck who's available at Staff button in menu.",
                                    "Warning!", JOptionPane.WARNING_MESSAGE);
                            txtStaffID.selectAll();
                            txtStaffID.replaceSelection("");
                            return;
                        }
                        Connection connection = ConnectionClass.connection();
                        String insertQuery = "INSERT INTO Class_allocation VALUES (? ,? ,? ,? ,? ,? )";
                        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                        preparedStatement.setString(1, txtEnrollmentID.getText());
                        preparedStatement.setString(2, tempSubjectID);
                        preparedStatement.setString(3, txtStaffID.getText());
                        preparedStatement.setString(4, tempStudentID);
                        preparedStatement.setString(5, tempClassID);
                        preparedStatement.setString(6, txtRoom.getText());

                        preparedStatement.executeUpdate();
                        if (showTime) {
                            show_allocation();
                            showTime = false;
                        } else {
                            model.setRowCount(0);
                            show_allocation();
                        }
                        JOptionPane.showMessageDialog(null, "Insert completed!");
                        connection.close();
                    } else {
                        txtEnrollmentID.selectAll();
                        txtEnrollmentID.replaceSelection("");
                    }
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else if (doing.equals("Update")) {
            if (txtEnrollmentID.getText().length() == 0 || txtStaffID.getText().length() == 0
                    || txtRoom.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "No field can be empty!",
                        "Warning!", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    if (!Checking_Input_Data.Check("enrollment_ID", txtEnrollmentID.getText(),
                            "Class_allocation", true)){
                        if (Checking_Input_Data.Check("staff_ID", txtStaffID.getText(), "Staff", true)){
                            JOptionPane.showMessageDialog(null,
                                    "This Staff is not available, \ncheck who's available at Staff button in menu.",
                                    "Warning!", JOptionPane.WARNING_MESSAGE);
                            txtStaffID.selectAll();
                            txtStaffID.replaceSelection("");
                            return;
                        }

                        Connection connection = ConnectionClass.connection();
                        String insertQuery = "UPDATE Class_allocation SET staff_ID = ?, room = ? WHERE enrollment_ID = ?";
                        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                        preparedStatement.setString(3, txtEnrollmentID.getText());
                        preparedStatement.setString(1, txtStaffID.getText());
                        preparedStatement.setString(2, txtRoom.getText());

                        preparedStatement.executeUpdate();
                        if (showTime) {
                            show_allocation();
                            showTime = false;
                        } else {
                            model.setRowCount(0);
                            show_allocation();
                        }
                        JOptionPane.showMessageDialog(null,
                                "Update completed! \nTips: Only Staff ID and Room can be updated!");
                        connection.close();
                    } else {
                        txtEnrollmentID.selectAll();
                        txtEnrollmentID.replaceSelection("");
                    }
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else if (doing.equals("Remove")) {
            if (txtEnrollmentID.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Enrollment ID cannot be empty!",
                        "Warning!", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    if (!Checking_Input_Data.Check("enrollment_ID", txtEnrollmentID.getText(),
                            "Class_allocation", true)){
                        Connection connection = ConnectionClass.connection();
                        String insertQuery = "DELETE FROM Class_allocation WHERE enrollment_ID = ?";
                        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                        preparedStatement.setString(1, txtEnrollmentID.getText());

                        preparedStatement.executeUpdate();
                        if (showTime) {
                           show_allocation();
                            showTime = false;
                        } else {
                            model.setRowCount(0);
                            show_allocation();
                        }
                        JOptionPane.showMessageDialog(null, "Remove completed!");
                        connection.close();
                    } else {
                        txtEnrollmentID.selectAll();
                        txtEnrollmentID.replaceSelection("");
                    }
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void txtStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Class_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Class_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Class_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Class_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Class_Allocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRun;
    private javax.swing.JComboBox<String> comboboxWhatToDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableShowAllocation;
    private javax.swing.JTextField txtEnrollmentID;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
