/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoool.management.system.Finance_Group;

import schoool.management.system.Arrangement_Group.Registration;
import schoool.management.system.Tool_Group.Checking_Input_Data;
import schoool.management.system.Tool_Group.ConnectionClass;
import schoool.management.system.Menu_Group.Welcome_Admin;
import schoool.management.system.Menu_Group.Welcome_Staff;
import schoool.management.system.Menu_Group.Welcome_Student;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.util.ArrayList;

/**
 * @author PC
 */
public class Staff_Salary extends javax.swing.JFrame {
    DefaultTableModel model;
    private static boolean showTime = true;
    private static int role = 0;
    private static String ID = null;
    private static int real_ID = 0;

    public static int getReal_ID() {
        return real_ID;
    }

    public static void setReal_ID(int real_ID) {
        Staff_Salary.real_ID = real_ID;
    }
    public static int getRole() {
        return role;
    }

    public static void setRole(int role) {
        Staff_Salary.role = role;
    }

    public static String getID() {
        return ID;
    }

    public static void setID(String ID) {
        Staff_Salary.ID = ID;
    }

    /**
     * Creates new form Staff_Salary
     */
    public Staff_Salary() {
        JLabel background = new JLabel(new ImageIcon("src/images/school theme 4.1.jpg"));
        setContentPane(background);
        initComponents();
        groupPaymentStatus = new ButtonGroup();
        groupPaymentStatus.add(btnYes);
        groupPaymentStatus.add(btnNo);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        if (role == 1){
            btnRun.setEnabled(false);
        }
    }

    public ArrayList<Salary> salaryArrayList() {
        ArrayList<Salary> salaryArrayList = new ArrayList<>();
        try {
            Connection connection = ConnectionClass.connection();
            String sql = "SELECT * FROM Staff_salary";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Salary salary;
            while (rs.next()) {
                salary = new Salary(
                        rs.getInt("staff_ID"),
                        rs.getString("staff_name"),
                        rs.getDouble("salary"),
                        rs.getString("payment_status"));
                salaryArrayList.add(salary);
            }
            connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return salaryArrayList;
    }

    public void show_salary() {
        ArrayList<Salary> list = salaryArrayList();
        model = (DefaultTableModel) tableShowSalary.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getStaff_ID();
            row[1] = list.get(i).getStaff_name();
            row[2] = list.get(i).getSalary();
            row[3] = list.get(i).getPayment_status();
            model.addRow(row);
        }
    }

    public void show_only(){
        ArrayList<Salary> salaries = new ArrayList<>();
        try {
            Connection connection = ConnectionClass.connection();
            String sql = "SELECT * FROM Staff_salary WHERE staff_ID = "
                    + real_ID;
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Salary salary;
            while (rs.next()) {
                salary = new Salary(
                        rs.getInt("staff_ID"),
                        rs.getString("staff_name"),
                        rs.getDouble("salary"),
                        rs.getString("payment_status"));
                salaries.add(salary);
            }
            connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        model = (DefaultTableModel) tableShowSalary.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < salaries.size(); i++) {
            row[0] = salaries.get(i).getStaff_ID();
            row[1] = salaries.get(i).getStaff_name();
            row[2] = salaries.get(i).getSalary();
            row[3] = salaries.get(i).getPayment_status();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPaymentStatus = new javax.swing.ButtonGroup();
        comboboxWhatToDo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtStaffName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        btnRun = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowSalary = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboboxWhatToDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboboxWhatToDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Update", "Add" }));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel2.setText("What to do:");

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel9.setText("Salary:");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel7.setText("Staff Name:");

        txtSalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtStaffName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel6.setText("Staff ID:");

        txtStaffID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRun.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        btnBrowse.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel10.setText("Payment Status:");

        btnYes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnYes.setText("Yes");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        btnNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNo.setText("No");

        tableShowSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name", "Salary", "Payment Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableShowSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableShowSalaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableShowSalary);

        jLabel1.setText("Note:");

        jLabel3.setText("- In this function, you are only able to modify or add a set of detail by Staff ID.");

        jLabel4.setText("- In case you do not remember Staff ID, then browse for it.");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel5.setText("Staff Salary");

        btnMenu.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 10)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu)
                        .addGap(260, 260, 260)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBrowse)
                                .addGap(222, 222, 222)
                                .addComponent(btnRun))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnYes)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnNo))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStaffName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtStaffID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(comboboxWhatToDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(btnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboboxWhatToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnYes)
                            .addComponent(btnNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBrowse)
                            .addComponent(btnRun)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        if (role == 1){
            if (showTime) {
                show_only();
                showTime = false;
            } else {
                model.setRowCount(0);
                show_only();
            }
        } else {
            if (showTime) {
                show_salary();
                showTime = false;
            } else {
                model.setRowCount(0);
                show_salary();
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        showTime = true;
        dispose();
        if (role == 0) {
            Welcome_Student.main(new String[]{});
        } else if (role == 1) {
            Welcome_Staff.main(new String[]{});
        } else {
            Welcome_Admin.main(new String[]{});
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void tableShowSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableShowSalaryMouseClicked
        // TODO add your handling code here:
        int i = tableShowSalary.getSelectedRow();
        TableModel model = tableShowSalary.getModel();
        txtStaffID.setText(model.getValueAt(i, 0).toString());
        txtStaffName.setText(model.getValueAt(i, 1).toString());
        txtSalary.setText(model.getValueAt(i, 2).toString());
        String temp = model.getValueAt(i, 3).toString();
        if (temp.equals("YES")) {
            btnYes.setSelected(true);
        } else if (temp.equals("NO")) {
            btnNo.setSelected(true);
        }
    }//GEN-LAST:event_tableShowSalaryMouseClicked

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
        if (comboboxWhatToDo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You need to choose an action!",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String doing = comboboxWhatToDo.getSelectedItem().toString();


        if (doing.equals("Add")) {
            if (txtStaffID.getText().length() == 0 || txtStaffName.getText().length() == 0
                    || txtSalary.getText().length() == 0 || (!btnYes.isSelected() && !btnNo.isSelected())) {
                JOptionPane.showMessageDialog(null, "No field can be empty!",
                        "Warning!", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    Double.parseDouble(txtSalary.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,
                            "Error salary input, it must be something like\"100.50\"!",
                            "Warning!", JOptionPane.WARNING_MESSAGE);
                    txtSalary.selectAll();
                    txtSalary.replaceSelection("");
                    return;
                }
                try {
                    if (Checking_Input_Data.Check("staff_ID", txtStaffID.getText(), "Staff_salary",
                            "This person has a salary!", false)
                            && Checking_Input_Data.Check("staff_name", txtStaffName.getText(), "Staff_salary",
                            "This person has a salary!", false)) {
                        Connection connection = ConnectionClass.connection();
                        String insertQuery = "INSERT INTO Staff_salary VALUES (? ,? ,? ,?)";
                        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                        preparedStatement.setString(1, txtStaffID.getText());
                        preparedStatement.setString(2, txtStaffName.getText());
                        preparedStatement.setString(3, txtSalary.getText());
                        if (btnYes.isSelected()){
                            preparedStatement.setString(4, "YES");
                        } else if (btnNo.isSelected()){
                            preparedStatement.setString(4, "NO");
                        }
                        preparedStatement.executeUpdate();
                        if (showTime) {
                            show_salary();
                            showTime = false;
                        } else {
                            model.setRowCount(0);
                            show_salary();
                        }
                        JOptionPane.showMessageDialog(null, "Insert completed!");
                        connection.close();
                    } else {
                        txtStaffID.selectAll();
                        txtStaffID.replaceSelection("");
                        txtStaffName.selectAll();
                        txtStaffName.replaceSelection("");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else if (doing.equals("Update")) {
            if (txtStaffID.getText().length() == 0 || txtStaffName.getText().length() == 0
                    || txtSalary.getText().length() == 0 || (!btnYes.isSelected() && !btnNo.isSelected())) {
                JOptionPane.showMessageDialog(null, "No field can be empty!",
                        "Warning!", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    Double.parseDouble(txtSalary.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,
                            "Error salary input, it must be something like\"100.50\"!",
                            "Warning!", JOptionPane.WARNING_MESSAGE);
                    txtSalary.selectAll();
                    txtSalary.replaceSelection("");
                    return;
                }
                try {
                    if (!Checking_Input_Data.Check("staff_ID", txtStaffID.getText(), "Staff_salary",
                            "Error ID! You update nobody's salary!", true)
                            || !Checking_Input_Data.Check("staff_name", txtStaffName.getText(), "Staff_salary",
                            "Error name! You update nobody's salary!", true)) {
                        Connection connection = ConnectionClass.connection();
                        String insertQuery =
                                "UPDATE Staff_salary SET salary = ?, payment_status = ? " +
                                        "WHERE staff_ID = ? OR staff_name = ?";
                        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                        preparedStatement.setString(1, txtSalary.getText());
                        if (btnYes.isSelected()){
                            preparedStatement.setString(2, "YES");
                        } else if (btnNo.isSelected()){
                            preparedStatement.setString(2, "NO");
                        }
                        preparedStatement.setString(3, txtStaffID.getText());
                        preparedStatement.setString(4, txtStaffName.getText());
                        preparedStatement.executeUpdate();
                        if (showTime) {
                            show_salary();
                            showTime = false;
                        } else {
                            model.setRowCount(0);
                            show_salary();
                        }
                        JOptionPane.showMessageDialog(null, "Update completed! " +
                                "\nTip: You can only update salary and payment status!");
                        connection.close();
                    } else {
                        txtStaffID.selectAll();
                        txtStaffID.replaceSelection("");
                        txtStaffName.selectAll();
                        txtStaffName.replaceSelection("");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_btnRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnMenu;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnRun;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.JComboBox<String> comboboxWhatToDo;
    private javax.swing.ButtonGroup groupPaymentStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableShowSalary;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtStaffName;
    // End of variables declaration//GEN-END:variables
}
